version: '2'

services:
  mysql:
    image: mariadb:latest
    container_name: mysql-sample
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    env_file:
      - docker/docker-compose-env/database.env
  redis:
    image: redis:alpine
    container_name: redis-sample
    command: ['redis-server', '--bind','0.0.0.0','--requirepass', 'testes','--port','6380']
    volumes:
      - redis-data:/data
  php:
    build:
      context: .
      dockerfile: ./docker/php8-fpm/Dockerfile
    image: sampleapitest-app:v4.0
    container_name: php-sample
    restart: on-failure
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - mysql
    command: bash -c "php artisan migrate && php-fpm"
    env_file:
      - docker/docker-compose-env/application.env
    links:
      - mysql
      - redis
    volumes:
     - .:/app:rw
  worker-queue:
    build:
      context: .
      dockerfile: ./docker/php8-fpm/Dockerfile
    image: sampleapiotra:php-worker-queue
    container_name: php-sample-worker-queue
    depends_on:
      - redis
      - mysql
    command: sh -c "php /app/artisan queue:work --verbose --tries=7 --timeout=90"
    restart: on-failure
    env_file:
      - docker/docker-compose-env/application.env
    links:
      - mysql
      - redis
    volumes:
      - .:/app:rw

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx-sample
    restart: on-failure
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./public/build/assets:/app/public/build/assets
    ports:
      - 443:443

volumes:
  frontendbuild-data:
    driver: "local"
  redis-data:
    driver: "local"
  mysql-data:
    driver: "local"
