services:
  mysql:
    image: mariadb:latest
    container_name: mysql-sample-user
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    env_file:
      - docker/docker-compose-env/database.env
  redis:
    image: redis:alpine
    container_name: redis-sample
    command: ['redis-server', '--bind','0.0.0.0','--requirepass', 'testes','--port','6380']
    volumes:
      - redis-data:/data
  php:
    build:
      context: .
      dockerfile: ./docker/php8-fpm/Dockerfile
    image: sampleapitest-app:v4.0
    container_name: php-sample-user
    restart: on-failure
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - mysql
    command: bash -c "php artisan migrate && php-fpm"
    env_file:
      - docker/docker-compose-env/application.env
    links:
      - mysql
      - redis
    volumes:
     - .:/app:rw
  worker-queue:
    build:
      context: .
      dockerfile: ./docker/php8-fpm/Dockerfile
    image: sampleapiotra:php-worker-queue
    container_name: php-sample-user-worker-queue
    depends_on:
      - redis
      - mysql
    command: sh -c "php /app/artisan queue:work --verbose --tries=7 --timeout=90"
    restart: on-failure
    env_file:
      - docker/docker-compose-env/application.env
    links:
      - mysql
      - redis
    volumes:
      - .:/app:rw

  webserver:
    build:
      context: .
      dockerfile: ./docker/webserver/dockerfile/webserver.dockerfile
    container_name: webserver-sample-user
    restart: on-failure
    volumes:
     - .:/app:rw
     - composer-vendor-data:/app/vendor:rw
     - vite-compiled-data:/app/public/build:rw
     - ./docker/webserver/startup/startup.sh:/app/startup.sh
    ports:
      - 80:80
      - 8003:8003
    depends_on:
      - mysql
      - redis
    env_file:
      - docker/docker-compose-env/application.env
    links:
      - mysql
      - redis

volumes:
  composer-vendor-data:
    driver: "local"
  vite-compiled-data:
    driver: "local"
  redis-data:
    driver: "local"
  mysql-data:
    driver: "local"
