version: '2'

services:
  mysql:
    image: mariadb:latest
    container_name: mysql-sample
    volumes:
      - ./data/mariadb-sample:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=testes
      - MYSQL_DATABASE=simple_user_area
      - MYSQL_USER=sandbox
      - MYSQL_PASSWORD=sandbox

  redis:
    image: redis:alpine
    container_name: redis-sample
    command: ['redis-server', '--bind','0.0.0.0','--requirepass', 'testes','--port','6380']
    volumes:
      - redis-data:/data
  php:
    build:
      context: .
      dockerfile: ./docker/php8-fpm/Dockerfile
    image: sampleapitest-app:v4.0
    container_name: php-sample
    depends_on:
      - redis
      - mysql
    command: bash -c "php artisan migrate && php-fpm"
    environment:
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      MYSQL_HOST: ${MYSQL_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DEBUG: 1
      REDIS_CLIENT: ${REDIS_CLIENT}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      CACHE_DRIVER: ${CACHE_DRIVER}
      SESSION_DRIVER: ${SESSION_DRIVER}
      LOG_CHANNEL: ${LOG_CHANNEL}
      LOG_STDERR_FORMATTER: ${LOG_STDERR_FORMATTER}
    links:
      - mysql
      - redis
    volumes:
     - .:/app:rw
  worker-queue:
    build:
      context: .
      dockerfile: ./docker/php8-fpm/Dockerfile
    image: sampleapiotra:php-worker-queue
    container_name: php-sample-worker-queue
    depends_on:
      - redis
      - mysql
    command: sh -c "php /app/artisan queue:work --verbose --tries=7 --timeout=90"
    environment:
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      MYSQL_HOST: ${MYSQL_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DEBUG: 1
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      REDIS_CLIENT: ${REDIS_CLIENT}
      CACHE_DRIVER: ${CACHE_DRIVER}
      SESSION_DRIVER: ${SESSION_DRIVER}
      LOG_CHANNEL: ${LOG_CHANNEL}
      LOG_STDERR_FORMATTER: ${LOG_STDERR_FORMATTER}
    links:
      - mysql
      - redis
    volumes:
      - .:/app:rw

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx-sample
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./public/build/assets:/app/public/build/assets
      - .:/app:rw
    ports:
      - 80:80
      - 443:443

volumes:
  redis-data:
    driver: "local"
  mysql-data:
    driver: "local"
